; NSIS post-install / post-uninstall hooks for OpenCluely Windows installer.
;
; On install completion we:
;   1. Drop a default .env next to the user's Start-Menu launcher
;   2. Offer to bootstrap the local Whisper environment if Python is on PATH
;
; This file is referenced from package.json build.nsis.include.
; It runs in the user's security context (UAC was already accepted).

!macro customInstall
  ; Create default .env in the install directory if missing.
  ; Electron will load .env from CWD; we drop a copy next to the EXE
  ; so first-time launches find a template the user can edit.
  IfFileExists "$INSTDIR\.env" have_env
    IfFileExists "$INSTDIR\env.example" have_template
      Goto done_env
    have_template:
      FileOpen $0 "$INSTDIR\.env" w
      FileWrite $0 "# Generated by OpenCluely installer on first launch$\r$\n"
      FileWrite $0 "# Edit this file or open Settings in the app to configure$\r$\n"
      FileWrite $0 "$\r$\n"
      FileWrite $0 "GEMINI_API_KEY=your_gemini_api_key_here$\r$\n"
      FileWrite $0 "SPEECH_PROVIDER=whisper$\r$\n"
      FileWrite $0 "WHISPER_COMMAND=$INSTDIR\.venv-whisper\Scripts\whisper.exe$\r$\n"
      FileWrite $0 "WHISPER_MODEL=turbo$\r$\n"
      FileWrite $0 "WHISPER_LANGUAGE=en$\r$\n"
      FileWrite $0 "WHISPER_SEGMENT_MS=4000$\r$\n"
      FileClose $0
      have_env:
  done_env:

  ; Detect Python on PATH; if found, silently create the Whisper venv.
  ; We don't prompt to keep the installer non-interactive.
  nsExec::ExecToLog 'cmd /c where python 2>nul'
  Pop $0
  StrCmp $0 "0" 0 no_python
    ; python is on PATH — try to create the venv
    nsExec::ExecToLog 'cmd /c python -m venv "$INSTDIR\.venv-whisper"'
    Pop $0
    StrCmp $0 "0" 0 venv_failed
      ; venv created — try to install whisper
      nsExec::ExecToLog 'cmd /c "$INSTDIR\.venv-whisper\Scripts\pip.exe" install --quiet openai-whisper'
      Pop $0
      Goto python_done
    venv_failed:
    no_python:
  python_done:
!macroend

!macro customUnInstall
  ; We deliberately do NOT delete .env or .venv-whisper on uninstall
  ; so users can preserve their config / model cache. Only the .exe
  ; and bundled resources get removed.
!macroend
